package com.tiger.dao;

import com.tiger.model.ContractAddress;
import com.tiger.model.ContractAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int countByExample(ContractAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByExample(ContractAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insert(ContractAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insertSelective(ContractAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    List<ContractAddress> selectByExample(ContractAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    ContractAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") ContractAddress record, @Param("example") ContractAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExample(@Param("record") ContractAddress record, @Param("example") ContractAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKeySelective(ContractAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_address
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKey(ContractAddress record);
}