package com.tiger.dao;

import com.tiger.model.QuartzTrigger;
import com.tiger.model.QuartzTriggerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuartzTriggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int countByExample(QuartzTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int deleteByExample(QuartzTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int insert(QuartzTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int insertSelective(QuartzTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    List<QuartzTrigger> selectByExample(QuartzTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    QuartzTrigger selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") QuartzTrigger record, @Param("example") QuartzTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int updateByExample(@Param("record") QuartzTrigger record, @Param("example") QuartzTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int updateByPrimaryKeySelective(QuartzTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    int updateByPrimaryKey(QuartzTrigger record);
}