package com.tiger.dao;

import com.tiger.model.SystemParam;
import com.tiger.model.SystemParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int countByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insert(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insertSelective(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    List<SystemParam> selectByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    SystemParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") SystemParam record, @Param("example") SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExample(@Param("record") SystemParam record, @Param("example") SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKeySelective(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKey(SystemParam record);
}