package com.tiger.dao;

import com.tiger.model.SystemParamType;
import com.tiger.model.SystemParamTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemParamTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int countByExample(SystemParamTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByExample(SystemParamTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insert(SystemParamType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insertSelective(SystemParamType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    List<SystemParamType> selectByExample(SystemParamTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    SystemParamType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") SystemParamType record, @Param("example") SystemParamTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExample(@Param("record") SystemParamType record, @Param("example") SystemParamTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKeySelective(SystemParamType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKey(SystemParamType record);
}