package com.tiger.dao;

import com.tiger.model.TerminalDevice;
import com.tiger.model.TerminalDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TerminalDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int countByExample(TerminalDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByExample(TerminalDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insert(TerminalDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insertSelective(TerminalDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    List<TerminalDevice> selectByExample(TerminalDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    TerminalDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") TerminalDevice record, @Param("example") TerminalDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExample(@Param("record") TerminalDevice record, @Param("example") TerminalDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKeySelective(TerminalDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKey(TerminalDevice record);
}