package com.tiger.dao;

import com.tiger.model.TruckType;
import com.tiger.model.TruckTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TruckTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int countByExample(TruckTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByExample(TruckTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insert(TruckType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insertSelective(TruckType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    List<TruckType> selectByExample(TruckTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    TruckType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") TruckType record, @Param("example") TruckTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExample(@Param("record") TruckType record, @Param("example") TruckTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKeySelective(TruckType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKey(TruckType record);
}