package com.tiger.dao;

import com.tiger.model.Truck;
import com.tiger.model.TruckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TruckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int countByExample(TruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByExample(TruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insert(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int insertSelective(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    List<Truck> selectByExample(TruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    Truck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") Truck record, @Param("example") TruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByExample(@Param("record") Truck record, @Param("example") TruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKeySelective(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    int updateByPrimaryKey(Truck record);
}