package com.tiger.model;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.organization_code
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String organizationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.business_license_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String businessLicenseNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.organization_code
     *
     * @return the value of company.organization_code
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.organization_code
     *
     * @param organizationCode the value for company.organization_code
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.business_license_number
     *
     * @return the value of company.business_license_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getBusinessLicenseNumber() {
        return businessLicenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.business_license_number
     *
     * @param businessLicenseNumber the value for company.business_license_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setBusinessLicenseNumber(String businessLicenseNumber) {
        this.businessLicenseNumber = businessLicenseNumber == null ? null : businessLicenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", organizationCode=").append(organizationCode);
        sb.append(", businessLicenseNumber=").append(businessLicenseNumber);
        sb.append("]");
        return sb.toString();
    }
}