package com.tiger.model;

import java.math.BigDecimal;

public class GoodsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.good_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer goodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.weight
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.volume
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.length
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private BigDecimal length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.width
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private BigDecimal width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.height
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private BigDecimal height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.description
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.good_unit
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer goodUnit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.id
     *
     * @return the value of goods_info.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.id
     *
     * @param id the value for goods_info.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.name
     *
     * @return the value of goods_info.name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.name
     *
     * @param name the value for goods_info.name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.good_type
     *
     * @return the value of goods_info.good_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.good_type
     *
     * @param goodType the value for goods_info.good_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setGoodType(Integer goodType) {
        this.goodType = goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.weight
     *
     * @return the value of goods_info.weight
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.weight
     *
     * @param weight the value for goods_info.weight
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.volume
     *
     * @return the value of goods_info.volume
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.volume
     *
     * @param volume the value for goods_info.volume
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.length
     *
     * @return the value of goods_info.length
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.length
     *
     * @param length the value for goods_info.length
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setLength(BigDecimal length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.width
     *
     * @return the value of goods_info.width
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.width
     *
     * @param width the value for goods_info.width
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setWidth(BigDecimal width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.height
     *
     * @return the value of goods_info.height
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.height
     *
     * @param height the value for goods_info.height
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.description
     *
     * @return the value of goods_info.description
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.description
     *
     * @param description the value for goods_info.description
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.good_unit
     *
     * @return the value of goods_info.good_unit
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getGoodUnit() {
        return goodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.good_unit
     *
     * @param goodUnit the value for goods_info.good_unit
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setGoodUnit(Integer goodUnit) {
        this.goodUnit = goodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", goodType=").append(goodType);
        sb.append(", weight=").append(weight);
        sb.append(", volume=").append(volume);
        sb.append(", length=").append(length);
        sb.append(", width=").append(width);
        sb.append(", height=").append(height);
        sb.append(", description=").append(description);
        sb.append(", goodUnit=").append(goodUnit);
        sb.append("]");
        return sb.toString();
    }
}