package com.tiger.model;

import java.util.Date;

public class QuartzTrigger {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.name
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.group_name
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.description
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.day
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.hour
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private Integer hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.minute
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private Integer minute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.second
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private Integer second;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.start_date
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.count
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.trigger_type
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private String triggerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_trigger.job
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    private String job;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.name
     *
     * @return the value of quartz_trigger.name
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.name
     *
     * @param name the value for quartz_trigger.name
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.group_name
     *
     * @return the value of quartz_trigger.group_name
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.group_name
     *
     * @param groupName the value for quartz_trigger.group_name
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.description
     *
     * @return the value of quartz_trigger.description
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.description
     *
     * @param description the value for quartz_trigger.description
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.day
     *
     * @return the value of quartz_trigger.day
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.day
     *
     * @param day the value for quartz_trigger.day
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.hour
     *
     * @return the value of quartz_trigger.hour
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.hour
     *
     * @param hour the value for quartz_trigger.hour
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.minute
     *
     * @return the value of quartz_trigger.minute
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public Integer getMinute() {
        return minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.minute
     *
     * @param minute the value for quartz_trigger.minute
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setMinute(Integer minute) {
        this.minute = minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.second
     *
     * @return the value of quartz_trigger.second
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public Integer getSecond() {
        return second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.second
     *
     * @param second the value for quartz_trigger.second
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setSecond(Integer second) {
        this.second = second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.start_date
     *
     * @return the value of quartz_trigger.start_date
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.start_date
     *
     * @param startDate the value for quartz_trigger.start_date
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.count
     *
     * @return the value of quartz_trigger.count
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.count
     *
     * @param count the value for quartz_trigger.count
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.trigger_type
     *
     * @return the value of quartz_trigger.trigger_type
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public String getTriggerType() {
        return triggerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.trigger_type
     *
     * @param triggerType the value for quartz_trigger.trigger_type
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType == null ? null : triggerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_trigger.job
     *
     * @return the value of quartz_trigger.job
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_trigger.job
     *
     * @param job the value for quartz_trigger.job
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_trigger
     *
     * @mbggenerated Fri Dec 02 13:04:44 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", groupName=").append(groupName);
        sb.append(", description=").append(description);
        sb.append(", day=").append(day);
        sb.append(", hour=").append(hour);
        sb.append(", minute=").append(minute);
        sb.append(", second=").append(second);
        sb.append(", startDate=").append(startDate);
        sb.append(", count=").append(count);
        sb.append(", triggerType=").append(triggerType);
        sb.append(", job=").append(job);
        sb.append("]");
        return sb.toString();
    }
}