package com.tiger.model;

import java.util.Date;

public class SystemUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.gender
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.nick_name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.identity_card
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.personal_phone
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String personalPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.home_phone
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String homePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.password
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.password_salt
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String passwordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_code
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.created_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.created_by
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.updated_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.user_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.company_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.driving_license_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer drivingLicenseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.email
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.id
     *
     * @return the value of system_user.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.id
     *
     * @param id the value for system_user.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_name
     *
     * @return the value of system_user.user_name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_name
     *
     * @param userName the value for system_user.user_name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.gender
     *
     * @return the value of system_user.gender
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.gender
     *
     * @param gender the value for system_user.gender
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.nick_name
     *
     * @return the value of system_user.nick_name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.nick_name
     *
     * @param nickName the value for system_user.nick_name
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.identity_card
     *
     * @return the value of system_user.identity_card
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.identity_card
     *
     * @param identityCard the value for system_user.identity_card
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.personal_phone
     *
     * @return the value of system_user.personal_phone
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getPersonalPhone() {
        return personalPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.personal_phone
     *
     * @param personalPhone the value for system_user.personal_phone
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setPersonalPhone(String personalPhone) {
        this.personalPhone = personalPhone == null ? null : personalPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.home_phone
     *
     * @return the value of system_user.home_phone
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.home_phone
     *
     * @param homePhone the value for system_user.home_phone
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone == null ? null : homePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.password
     *
     * @return the value of system_user.password
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.password
     *
     * @param password the value for system_user.password
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.password_salt
     *
     * @return the value of system_user.password_salt
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.password_salt
     *
     * @param passwordSalt the value for system_user.password_salt
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt == null ? null : passwordSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_code
     *
     * @return the value of system_user.user_code
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_code
     *
     * @param userCode the value for system_user.user_code
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setUserCode(Integer userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.created_time
     *
     * @return the value of system_user.created_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.created_time
     *
     * @param createdTime the value for system_user.created_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.created_by
     *
     * @return the value of system_user.created_by
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.created_by
     *
     * @param createdBy the value for system_user.created_by
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.updated_time
     *
     * @return the value of system_user.updated_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.updated_time
     *
     * @param updatedTime the value for system_user.updated_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.user_type
     *
     * @return the value of system_user.user_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.user_type
     *
     * @param userType the value for system_user.user_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.company_id
     *
     * @return the value of system_user.company_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.company_id
     *
     * @param companyId the value for system_user.company_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.driving_license_type
     *
     * @return the value of system_user.driving_license_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getDrivingLicenseType() {
        return drivingLicenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.driving_license_type
     *
     * @param drivingLicenseType the value for system_user.driving_license_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setDrivingLicenseType(Integer drivingLicenseType) {
        this.drivingLicenseType = drivingLicenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.email
     *
     * @return the value of system_user.email
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.email
     *
     * @param email the value for system_user.email
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_user
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", gender=").append(gender);
        sb.append(", nickName=").append(nickName);
        sb.append(", identityCard=").append(identityCard);
        sb.append(", personalPhone=").append(personalPhone);
        sb.append(", homePhone=").append(homePhone);
        sb.append(", password=").append(password);
        sb.append(", passwordSalt=").append(passwordSalt);
        sb.append(", userCode=").append(userCode);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", userType=").append(userType);
        sb.append(", companyId=").append(companyId);
        sb.append(", drivingLicenseType=").append(drivingLicenseType);
        sb.append(", email=").append(email);
        sb.append("]");
        return sb.toString();
    }
}