package com.tiger.model;

public class SystemParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_param.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_param.param_value
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_param.param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer paramType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_param.id
     *
     * @return the value of system_param.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_param.id
     *
     * @param id the value for system_param.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_param.param_value
     *
     * @return the value of system_param.param_value
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_param.param_value
     *
     * @param paramValue the value for system_param.param_value
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_param.param_type
     *
     * @return the value of system_param.param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_param.param_type
     *
     * @param paramType the value for system_param.param_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setParamType(Integer paramType) {
        this.paramType = paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_param
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", paramValue=").append(paramValue);
        sb.append(", paramType=").append(paramType);
        sb.append("]");
        return sb.toString();
    }
}