package com.tiger.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TruckTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public TruckTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTruckNumberIsNull() {
            addCriterion("truck_number is null");
            return (Criteria) this;
        }

        public Criteria andTruckNumberIsNotNull() {
            addCriterion("truck_number is not null");
            return (Criteria) this;
        }

        public Criteria andTruckNumberEqualTo(String value) {
            addCriterion("truck_number =", value, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberNotEqualTo(String value) {
            addCriterion("truck_number <>", value, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberGreaterThan(String value) {
            addCriterion("truck_number >", value, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberGreaterThanOrEqualTo(String value) {
            addCriterion("truck_number >=", value, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberLessThan(String value) {
            addCriterion("truck_number <", value, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberLessThanOrEqualTo(String value) {
            addCriterion("truck_number <=", value, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberLike(String value) {
            addCriterion("truck_number like", value, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberNotLike(String value) {
            addCriterion("truck_number not like", value, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberIn(List<String> values) {
            addCriterion("truck_number in", values, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberNotIn(List<String> values) {
            addCriterion("truck_number not in", values, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberBetween(String value1, String value2) {
            addCriterion("truck_number between", value1, value2, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckNumberNotBetween(String value1, String value2) {
            addCriterion("truck_number not between", value1, value2, "truckNumber");
            return (Criteria) this;
        }

        public Criteria andTruckLengthIsNull() {
            addCriterion("truck_length is null");
            return (Criteria) this;
        }

        public Criteria andTruckLengthIsNotNull() {
            addCriterion("truck_length is not null");
            return (Criteria) this;
        }

        public Criteria andTruckLengthEqualTo(BigDecimal value) {
            addCriterion("truck_length =", value, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthNotEqualTo(BigDecimal value) {
            addCriterion("truck_length <>", value, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthGreaterThan(BigDecimal value) {
            addCriterion("truck_length >", value, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("truck_length >=", value, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthLessThan(BigDecimal value) {
            addCriterion("truck_length <", value, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("truck_length <=", value, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthIn(List<BigDecimal> values) {
            addCriterion("truck_length in", values, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthNotIn(List<BigDecimal> values) {
            addCriterion("truck_length not in", values, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("truck_length between", value1, value2, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckLengthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("truck_length not between", value1, value2, "truckLength");
            return (Criteria) this;
        }

        public Criteria andTruckWidthIsNull() {
            addCriterion("truck_width is null");
            return (Criteria) this;
        }

        public Criteria andTruckWidthIsNotNull() {
            addCriterion("truck_width is not null");
            return (Criteria) this;
        }

        public Criteria andTruckWidthEqualTo(BigDecimal value) {
            addCriterion("truck_width =", value, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthNotEqualTo(BigDecimal value) {
            addCriterion("truck_width <>", value, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthGreaterThan(BigDecimal value) {
            addCriterion("truck_width >", value, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("truck_width >=", value, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthLessThan(BigDecimal value) {
            addCriterion("truck_width <", value, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("truck_width <=", value, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthIn(List<BigDecimal> values) {
            addCriterion("truck_width in", values, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthNotIn(List<BigDecimal> values) {
            addCriterion("truck_width not in", values, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("truck_width between", value1, value2, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckWidthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("truck_width not between", value1, value2, "truckWidth");
            return (Criteria) this;
        }

        public Criteria andTruckHeightIsNull() {
            addCriterion("truck_height is null");
            return (Criteria) this;
        }

        public Criteria andTruckHeightIsNotNull() {
            addCriterion("truck_height is not null");
            return (Criteria) this;
        }

        public Criteria andTruckHeightEqualTo(BigDecimal value) {
            addCriterion("truck_height =", value, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightNotEqualTo(BigDecimal value) {
            addCriterion("truck_height <>", value, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightGreaterThan(BigDecimal value) {
            addCriterion("truck_height >", value, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("truck_height >=", value, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightLessThan(BigDecimal value) {
            addCriterion("truck_height <", value, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("truck_height <=", value, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightIn(List<BigDecimal> values) {
            addCriterion("truck_height in", values, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightNotIn(List<BigDecimal> values) {
            addCriterion("truck_height not in", values, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("truck_height between", value1, value2, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckHeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("truck_height not between", value1, value2, "truckHeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightIsNull() {
            addCriterion("truck_weight is null");
            return (Criteria) this;
        }

        public Criteria andTruckWeightIsNotNull() {
            addCriterion("truck_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTruckWeightEqualTo(BigDecimal value) {
            addCriterion("truck_weight =", value, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightNotEqualTo(BigDecimal value) {
            addCriterion("truck_weight <>", value, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightGreaterThan(BigDecimal value) {
            addCriterion("truck_weight >", value, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("truck_weight >=", value, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightLessThan(BigDecimal value) {
            addCriterion("truck_weight <", value, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("truck_weight <=", value, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightIn(List<BigDecimal> values) {
            addCriterion("truck_weight in", values, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightNotIn(List<BigDecimal> values) {
            addCriterion("truck_weight not in", values, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("truck_weight between", value1, value2, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTruckWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("truck_weight not between", value1, value2, "truckWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightIsNull() {
            addCriterion("transport_weight is null");
            return (Criteria) this;
        }

        public Criteria andTransportWeightIsNotNull() {
            addCriterion("transport_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTransportWeightEqualTo(BigDecimal value) {
            addCriterion("transport_weight =", value, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightNotEqualTo(BigDecimal value) {
            addCriterion("transport_weight <>", value, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightGreaterThan(BigDecimal value) {
            addCriterion("transport_weight >", value, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("transport_weight >=", value, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightLessThan(BigDecimal value) {
            addCriterion("transport_weight <", value, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("transport_weight <=", value, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightIn(List<BigDecimal> values) {
            addCriterion("transport_weight in", values, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightNotIn(List<BigDecimal> values) {
            addCriterion("transport_weight not in", values, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("transport_weight between", value1, value2, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("transport_weight not between", value1, value2, "transportWeight");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeIsNull() {
            addCriterion("transport_volume is null");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeIsNotNull() {
            addCriterion("transport_volume is not null");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeEqualTo(BigDecimal value) {
            addCriterion("transport_volume =", value, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeNotEqualTo(BigDecimal value) {
            addCriterion("transport_volume <>", value, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeGreaterThan(BigDecimal value) {
            addCriterion("transport_volume >", value, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("transport_volume >=", value, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeLessThan(BigDecimal value) {
            addCriterion("transport_volume <", value, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("transport_volume <=", value, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeIn(List<BigDecimal> values) {
            addCriterion("transport_volume in", values, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeNotIn(List<BigDecimal> values) {
            addCriterion("transport_volume not in", values, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("transport_volume between", value1, value2, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andTransportVolumeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("transport_volume not between", value1, value2, "transportVolume");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthIsNull() {
            addCriterion("loading_length is null");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthIsNotNull() {
            addCriterion("loading_length is not null");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthEqualTo(String value) {
            addCriterion("loading_length =", value, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthNotEqualTo(String value) {
            addCriterion("loading_length <>", value, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthGreaterThan(String value) {
            addCriterion("loading_length >", value, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthGreaterThanOrEqualTo(String value) {
            addCriterion("loading_length >=", value, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthLessThan(String value) {
            addCriterion("loading_length <", value, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthLessThanOrEqualTo(String value) {
            addCriterion("loading_length <=", value, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthLike(String value) {
            addCriterion("loading_length like", value, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthNotLike(String value) {
            addCriterion("loading_length not like", value, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthIn(List<String> values) {
            addCriterion("loading_length in", values, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthNotIn(List<String> values) {
            addCriterion("loading_length not in", values, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthBetween(String value1, String value2) {
            addCriterion("loading_length between", value1, value2, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andLoadingLengthNotBetween(String value1, String value2) {
            addCriterion("loading_length not between", value1, value2, "loadingLength");
            return (Criteria) this;
        }

        public Criteria andFuelTypeIsNull() {
            addCriterion("fuel_type is null");
            return (Criteria) this;
        }

        public Criteria andFuelTypeIsNotNull() {
            addCriterion("fuel_type is not null");
            return (Criteria) this;
        }

        public Criteria andFuelTypeEqualTo(Integer value) {
            addCriterion("fuel_type =", value, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeNotEqualTo(Integer value) {
            addCriterion("fuel_type <>", value, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeGreaterThan(Integer value) {
            addCriterion("fuel_type >", value, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fuel_type >=", value, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeLessThan(Integer value) {
            addCriterion("fuel_type <", value, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeLessThanOrEqualTo(Integer value) {
            addCriterion("fuel_type <=", value, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeIn(List<Integer> values) {
            addCriterion("fuel_type in", values, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeNotIn(List<Integer> values) {
            addCriterion("fuel_type not in", values, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeBetween(Integer value1, Integer value2) {
            addCriterion("fuel_type between", value1, value2, "fuelType");
            return (Criteria) this;
        }

        public Criteria andFuelTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("fuel_type not between", value1, value2, "fuelType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIsNull() {
            addCriterion("driver_type is null");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIsNotNull() {
            addCriterion("driver_type is not null");
            return (Criteria) this;
        }

        public Criteria andDriverTypeEqualTo(Integer value) {
            addCriterion("driver_type =", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotEqualTo(Integer value) {
            addCriterion("driver_type <>", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeGreaterThan(Integer value) {
            addCriterion("driver_type >", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("driver_type >=", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeLessThan(Integer value) {
            addCriterion("driver_type <", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeLessThanOrEqualTo(Integer value) {
            addCriterion("driver_type <=", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIn(List<Integer> values) {
            addCriterion("driver_type in", values, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotIn(List<Integer> values) {
            addCriterion("driver_type not in", values, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeBetween(Integer value1, Integer value2) {
            addCriterion("driver_type between", value1, value2, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("driver_type not between", value1, value2, "driverType");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierIsNull() {
            addCriterion("truck_supplier is null");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierIsNotNull() {
            addCriterion("truck_supplier is not null");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierEqualTo(Integer value) {
            addCriterion("truck_supplier =", value, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierNotEqualTo(Integer value) {
            addCriterion("truck_supplier <>", value, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierGreaterThan(Integer value) {
            addCriterion("truck_supplier >", value, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierGreaterThanOrEqualTo(Integer value) {
            addCriterion("truck_supplier >=", value, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierLessThan(Integer value) {
            addCriterion("truck_supplier <", value, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierLessThanOrEqualTo(Integer value) {
            addCriterion("truck_supplier <=", value, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierIn(List<Integer> values) {
            addCriterion("truck_supplier in", values, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierNotIn(List<Integer> values) {
            addCriterion("truck_supplier not in", values, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierBetween(Integer value1, Integer value2) {
            addCriterion("truck_supplier between", value1, value2, "truckSupplier");
            return (Criteria) this;
        }

        public Criteria andTruckSupplierNotBetween(Integer value1, Integer value2) {
            addCriterion("truck_supplier not between", value1, value2, "truckSupplier");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table truck_type
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 07 09:27:22 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table truck_type
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}