package com.tiger.model;

import java.util.Date;

public class Truck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.truck_type_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer truckTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.is_publish
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Boolean isPublish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.vin_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String vinNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.car_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String carNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.engine_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String engineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer terminalDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.comments
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.license_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private String licenseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.created_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truck.user_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.id
     *
     * @return the value of truck.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.id
     *
     * @param id the value for truck.id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.truck_type_id
     *
     * @return the value of truck.truck_type_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getTruckTypeId() {
        return truckTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.truck_type_id
     *
     * @param truckTypeId the value for truck.truck_type_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setTruckTypeId(Integer truckTypeId) {
        this.truckTypeId = truckTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.is_publish
     *
     * @return the value of truck.is_publish
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Boolean getIsPublish() {
        return isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.is_publish
     *
     * @param isPublish the value for truck.is_publish
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setIsPublish(Boolean isPublish) {
        this.isPublish = isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.vin_number
     *
     * @return the value of truck.vin_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getVinNumber() {
        return vinNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.vin_number
     *
     * @param vinNumber the value for truck.vin_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setVinNumber(String vinNumber) {
        this.vinNumber = vinNumber == null ? null : vinNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.car_number
     *
     * @return the value of truck.car_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.car_number
     *
     * @param carNumber the value for truck.car_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.engine_number
     *
     * @return the value of truck.engine_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getEngineNumber() {
        return engineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.engine_number
     *
     * @param engineNumber the value for truck.engine_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setEngineNumber(String engineNumber) {
        this.engineNumber = engineNumber == null ? null : engineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.terminal_device
     *
     * @return the value of truck.terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getTerminalDevice() {
        return terminalDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.terminal_device
     *
     * @param terminalDevice the value for truck.terminal_device
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setTerminalDevice(Integer terminalDevice) {
        this.terminalDevice = terminalDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.comments
     *
     * @return the value of truck.comments
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.comments
     *
     * @param comments the value for truck.comments
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.license_number
     *
     * @return the value of truck.license_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.license_number
     *
     * @param licenseNumber the value for truck.license_number
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber == null ? null : licenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.created_time
     *
     * @return the value of truck.created_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.created_time
     *
     * @param createdTime the value for truck.created_time
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truck.user_id
     *
     * @return the value of truck.user_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truck.user_id
     *
     * @param userId the value for truck.user_id
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truck
     *
     * @mbggenerated Wed Dec 07 09:27:22 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", truckTypeId=").append(truckTypeId);
        sb.append(", isPublish=").append(isPublish);
        sb.append(", vinNumber=").append(vinNumber);
        sb.append(", carNumber=").append(carNumber);
        sb.append(", engineNumber=").append(engineNumber);
        sb.append(", terminalDevice=").append(terminalDevice);
        sb.append(", comments=").append(comments);
        sb.append(", licenseNumber=").append(licenseNumber);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}